name: 'SBOM Scanner'
description: 'Scan a GitHub org and generate an inventory / bill-of-materials JSON dataset'
inputs:
  token:
    description: >
      Personal access token (PAT) used to fetch repository config information.
      This is the token only, without the user/actor prefix
    required: true
  tokenActor:
    description: 'The username which the PAT belongs to'
    required: true
  organizations:
    description: 'Comma-separated list of organizations to scan'
    required: true
  repositoryWhitelist:
    description: 'Comma-separated list of repositories to scan, default is to scan the entire organization'
    default: ''
  manifestFilename:
    description: 'Name of the manifest file to fetch from each repository'
    default: 'manifest.yml'
  scanners:
    description: 'Comma-separated list of scanners to enable, defaults to only manifest/github'
    default: ''
  githubUrl:
    description: 'The base url of the github instance, defaults to https://www.github.com'
    default: 'https://www.github.com'
  githubRawUrl:
    description: 'The base url for fetching raw files from an instance, defaults to https://raw.github.com'
    default: 'https://raw.github.com'
  outputDataFile:
    description: 'The name of the data file generated by the scanner'
    default: 'sbom.json'
  jenkinsUser:
    description: 'The username associated with the Jenkins token'
    default: ''
  jenkinsToken:
    description: 'Jenkins API access token (generated from Profile/Configure)'
    default: ''
  veracodeApiId:
    description: 'Vercode API ID'
  veracodeApiKey:
    description: 'Veracode API Key'
    default: ''
  veracodeScaWorkspace:
    description: 'Veracode SCA Workspace Name (agent-based)'
    default: ''
runs:
  using: node16
  main: dist/index.cjs
  post: dist/index.cjs
