name: Build and Test

on:
  pull_request:
  push:
    branches:
      - main
      - dev
      - release/*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: 16.x
      - uses: actions/checkout@v3
      - run: npm run format-check
      - run: npm run lint
      - run: npm run dist

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: 16.x
      - uses: actions/checkout@v3
      - name: Test Action
        uses: ./
        with:
          token: ${{ github.token }}
          token_actor: ${{ github.actor }}
          organizations: sharpbits
      - name: Verify Test
        shell: bash
        run: ./github/workflows/verify-test.sh
