name: Build and Test

on:
  pull_request:
  push:
    branches:
      - main
      - dev
      - release/*
      - ci-test
  workflow_dispatch: 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: 16.x
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.os }}-node_mod-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node_mod-
      - run: |
          npm i
          npm run format-check
          npm run lint
          npm run dist
      - uses: actions/upload-artifact@v3
        with:
          name: package
          path: |
            package.json
            package-lock.json
            action.yml
      - uses: actions/upload-artifact@v3
        with:
          name: dist
          path: dist

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: 16.x
      - uses: actions/download-artifact@v3
        with:
          name: package
      - uses: actions/download-artifact@v3
        with:
          name: dist
          path: dist
      - name: Test Action
        uses: ./
        with:
          token: ${{ github.token }}
          tokenActor: ${{ github.actor }}
          organizations: sharpbits
      - name: Verify Test
        shell: bash
        run: node .github/workflows/verify.js
